import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useRef } from "react";
import styles from "../styles/Home.module.css";

const botones = [
  {
    descripcion: "Caballo",
    imagen: "/caballo.png",
    sonido: "caballo.mp3",
  },
  {
    descripcion: "Vaca",
    imagen: "/vaca.png",
    sonido: "vaca.mp3",
  },
  {
    descripcion: "Lapiz",
    imagen: "/lapiz.png",
    sonido: "lapiz.mp3",
  },
];

function Boton(params) {
  const { boton } = params;
  let audioRef = React.createRef();

  const [play, setPlay] = React.useState(false);

  React.useEffect(() => {
    if (play) {
      audioRef.current.play();
      console.log("hola");
    }
    setPlay(false);
  }, [play, audioRef]);

  return (
    <a className={styles.card} onClick={() => setPlay(true)}>
      <img src={boton.imagen} alt={boton.descripcion} width="150px" />
      <audio ref={audioRef}>
        <source src={boton.sonido} type="audio/mpeg" />
        Your browser does not support the audio element.
      </audio>
      <h2 align="center">{boton.descripcion}</h2>
    </a>
  );
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sonido de nombres</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Toca una imagen &#129409;</h1>
        <div className={styles.grid}>
          {botones.map((boton) => (
            <Boton boton={boton} key={boton.descripcion} />
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
